server:
  port: 12811

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12800/eureka/

zuul:
  AccessFilter:
    pre: disable #禁用AccessFilter
  # retryable: false #挂壁关闭全局重试机制
  addHostHeader: true # 开启路由转发前为请求设置Host头信息，防止在后台服务返回重定向时指向了具体服务实例地址
  routes:
    service-chat:
      path: /service-chat/**
      serviceId: service-chat # 单机模式时：url: http://localhost:12820/ # 使用serviceId默认开启hystrix和ribbon功能
      retryable: false # 当路由转发请求超时，zuul会发起重试，设置false关闭重试机制
      customSensitiveHeade: true #开启Http请求头敏感信息传递，包括Cookie、Set-Cookie、Autorization
      # sensitiveHeaders: Cookie 方法二
  ignored-patterns: # 忽略路由配置
    /**/hello/**
